import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/layout/navbar";
import { navData } from "@/data/data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shivam Patel - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <FloatingNav navItems={navData} />
          <div className="z-1 absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-6/7 w-[60vw] h-[80vh] md:w-[40vw] md:h-[90vh] lg:w-[40vw] lg:h-[90vh] rounded-full blur-2xl sm:blur-3xl bg-gradient-to-r via-purple-400/80 from-orange-400/80 to-blue-400/80 dark:from-orange-400/60 dark:via-purple-400/60 dark:to-blue-400/60 mixed-blend-multiply" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
